USE DB_PRODUCTION;

 DROP TABLE IF EXISTS dbo.TB_LAYOUT_HISTORY_STOREPROCEDURE 	;
 DROP TABLE IF EXISTS dbo.TB_LOG_SP_GENERAL_CONTROL			;
 DROP TABLE IF EXISTS dbo.TB_LOG_SP_SENTENCE_CONTROL 		;
 DROP TABLE IF EXISTS dbo.TB_LOG_STATE						;
 DROP TABLE IF EXISTS dbo.TB_LAYOUT_STOREPROCEDURE			;


CREATE TABLE dbo.TB_LAYOUT_STOREPROCEDURE (
	LayoutID			INT NOT NULL	PRIMARY KEY IDENTITY(1000,1),
	LayoutSP			VARCHAR(50)		UNIQUE	NOT NULL,
	UserDB				VARCHAR(100)	NOT NULL,
	NameDB				VARCHAR(100)	NOT NULL,
	NameSP				VARCHAR(100)	NOT NULL,
	DescriptionSP		VARCHAR(1000)	NOT NULL,
	Parameter01			VARCHAR(100),
	Parameter02			VARCHAR(100),
	Parameter03			VARCHAR(100),
	Parameter04			VARCHAR(100),
	CreationDate		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdateDate			DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);



CREATE TABLE dbo.TB_LAYOUT_HISTORY_STOREPROCEDURE (
	LayoutStore			INT NOT NULL PRIMARY KEY IDENTITY(1000000,1),
	LayoutID			INT NOT NULL,
	LayoutSP			VARCHAR(50)		NOT NULL,
	UserDB				VARCHAR(100)	NOT NULL,
	NameDB				VARCHAR(100)	NOT NULL,
	NameSP				VARCHAR(100)	NOT NULL,
	DescriptionSP		VARCHAR(1000)	NOT NULL,
	Parameter01			VARCHAR(100),
	Parameter02			VARCHAR(100),
	Parameter03			VARCHAR(100),
	Parameter04			VARCHAR(100),
	CreationDate		DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	StateSP				BIT NOT NULL DEFAULT 1,

	FOREIGN KEY (LayoutID) REFERENCES dbo.TB_LAYOUT_STOREPROCEDURE(LayoutID)
);

CREATE TABLE dbo.TB_LOG_STATE (
	StateExecID			INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Description]		VARCHAR(50)		NOT NULL,
);


CREATE TABLE dbo.TB_LOG_SP_GENERAL_CONTROL (
	ExecStore		BIGINT NOT NULL PRIMARY KEY IDENTITY(1000000000,1),
	LayoutID		INT NOT NULL,
	LayoutSP		VARCHAR(50)		NOT NULL,
	UserDB			VARCHAR(100)	NOT NULL,
	StateExecID		INT NOT NULL ,
	IniDate			DATETIME,
	EndDate			DATETIME,
	NumRowsUPD		INTEGER,
	NumRowsINS		INTEGER,
	DescError		VARCHAR(1000),
	CreationDate	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (LayoutID) REFERENCES dbo.TB_LAYOUT_STOREPROCEDURE(LayoutID),
	FOREIGN KEY (StateExecID) REFERENCES dbo.TB_LOG_STATE(StateExecID)
);



CREATE TABLE dbo.TB_LOG_SP_SENTENCE_CONTROL (
	SentStore		BIGINT NOT NULL PRIMARY KEY IDENTITY(1000000000,1),
	LayoutID		INT NOT NULL,
	LayoutSP		VARCHAR(50)		NOT NULL,
	Sentence		VARCHAR(50)		NOT NULL,
	[State]			INT NOT NULL ,
	IniDate			DATETIME,
	EndDate			DATETIME,
	FOREIGN KEY (LayoutID) REFERENCES dbo.TB_LAYOUT_STOREPROCEDURE(LayoutID),
	FOREIGN KEY ([State]) REFERENCES dbo.TB_LOG_STATE(StateExecID)
);




